apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: reynanbelendevs/kube-demo-tasks:10
        env:
        # variable in kubernetes wil lalways overwrite the env in docker if has the same name
        - name: AUTH_ADDRESS
          # value: #cluster ip
          #Note: you can use service name as a domain to communicate with different pod
          value: "auth-service.default"
        - name: TASKS_FOLDER
          value: tasks
# - name: auth
#   image: reynanbelendevs/kub-demo-auth:latest
#
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000


